### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by ghost** [altf4/libmelee#1]
Dude, this is an awesome idea! If you want some help, don't hesitate to share the roadmap :smiley:

**Comment by altf4** [comment]
I'm about to make the first real commit. Standby for that. Hopefully within a day or two. I'm sure it will need some testing once it's in, so feel free to give it a try.

Windows support won't be there, for sure. I'll make a separate Issue for this, but dolphin will need some patches to make Windows support work.

**Comment by altf4** [comment]
The API is up and mostly running as of b98b75571da075b149eb5dfbdfcaff0369f3bd27

I'll post some specific Issues for requests for programming help. At the very least, give it a try and let me know how it works for you.
