### ISSUE TITLE
AI state cursor not updating

### ISSUE THREAD

**Issue by ghost** [altf4/libmelee#11]
In the character selection screen, it loops in the following block:
```python
#Move up if we're too low
if ai_state.cursor_y < target_y - wiggleroom:
    controller.tilt_analog(enums.Button.BUTTON_MAIN, .5, 1)
     return
```

being, and not updating:
```
cursor_y: 1.9197228441864264e-40
cursor_x: 1.9196667922478534e-40
```

My version is:
```
─── dolphin-emu-nogui -version
Dolphin [memorywatcher] 5.0-523
```

**Comment by altf4** [comment]
I just pushed a new version of libmelee, try it with that. (v0.0.7) It incorporates some improvements I made yesterday around character selection

**Comment by ghost** [comment]
No. It didn't work :disappointed:.

Could it be that I'm running 20XX instead of a vanilla ISO?

**Comment by altf4** [comment]
Oh yea, for sure. All of the memory locations are based on the Melee version being v1.02 NTSC. Everything will be wrong if you mess with that.

**Comment by ghost** [comment]
Totally, @altf4, my bad. It works awesome. :beers:
