### ISSUE TITLE
unknown pointer crash

### ISSUE THREAD

**Issue by neale** [altf4/libmelee#13]
I'm running into a problem with example.py
As far as I can tell, the setup looks good. Everything looks the same as it did when I used smashbot. 
I recompiled the linked dolphin, and it loads melee 1.02 fine. 

However when running example.py: Dolpgin can't start Melee as it errors out immediately with
Unknown Pointer 0x10000066 PC 0x8000522c LR 0x00000000

I can't find anyone else who has had this specific issue with Melee, only Paper Mario. 
Any thoughts?

EDIT more info. This is specifically something that happens to dolphin itself upon running example for the first time that renders it unusable. But I can't find what happens in dolphin.py (I'm guessing) that causes it

**Comment by altf4** [comment]
That error happens when dolphin tries to read an address in MemoryWatcher but it's a bad pointer, so it panics. That would happen if you had Melee running and then switched games, for instance.

I actually fixed this bug in the version of dolphin that you need for libmelee, so I highly suspect that you're accidentally not using the right version of dolphin.

Maybe you made the same (understandable) mistake as https://github.com/altf4/libmelee/issues/12

I have to get around to fixing that link...

**Comment by neale** [comment]
Nice! I saw that but I wasn't sure if it directly applied. It is indeed a problem with my memory watcher.

**Comment by azhu7** [comment]
I am having a similar issue with bad pointers. Dolphin is crashing in MemoryWatcher when it calls ChasePointer with the "projectiles" address. It also crashes for "stage_select_cursor_x" and "stage_select_cursor_y." As I understand it, MemoryWatcher::ChasePointer accesses memory[memory[address + offset] + offset]...etc.

I am running Ubuntu 16.0, and run dolphin from terminal with `sudo dolphin-emu`. Dolphin starts fine, but when I run melee, that is when it crashes. Melee is the only game I've run with Dolphin.

Any help would be greatly appreciated! Let me know if there is any more info I can provide.

**Comment by altf4** [comment]
What exact version is Dolphin? Go into the About menu in the gui.

**Comment by azhu7** [comment]
5.0-1171

**Comment by altf4** [comment]
Looks like you're not using the new custom version of Dolphin that libmelee asks you to build from source.

Your version ought to look like this:

![image](https://user-images.githubusercontent.com/609563/29752047-7946b178-8b0b-11e7-98d0-099324a4e809.png)

**Comment by azhu7** [comment]
Ah, didn't realize the version was on a different branch. It is working now, thank you!
