### ISSUE TITLE
Scope of project- modifying memory address values

### ISSUE THREAD

**Issue by flux627** [altf4/libmelee#15]
I am interested in adding the ability to modify game memory state (in order to implement training programs, among other things). Two questions:

1. Would the project owner (@altf4) be open to expanding the scope of the project to include this, or should I create my own fork?

2. Does Dolphin provide any mechanism for modifying memory address values?

**Comment by altf4** [comment]
The answer to question 2 is "not currently". You could, I guess, add support for that yourself within dolphin. That'd be the easiest way. I wouldn't have an issue supporting it within libmelee if you got a PR accepted by them.

Buuuut, maybe there's an easier way to accomplish what you want? I don't know exactly what you want to make in terms of "training programs", but I imagine you could just as easily set it all up with a bot, anyway.

IE: If you want to make a thing to practice tech chases, just make a bot that randomly does tech options.

**Comment by flux627** [comment]
Well, being able to programmatically save/load savestates would cover a lot of my use-cases. The idea is to be able to go back to a set-up situation over and over again without having to manually set it up every time.

There must be a way to programmatically control savestates, yes?

One fun use-case for memory modification would be to create "melee games" where you create games within the melee engine, setting your own rules and win conditions. Something like "Mr. Saturn Soccer". Or think of Break the Targets, or Home Run Contest, or Event Mode. The ability to create new games like this could be really fun.

**Comment by altf4** [comment]
Dolphin definitely has savestates. There may or may not be a programmatic way of interfacing with them. I've never tried. Talk to the devs on Freenode at #dolphin-dev. They would know.

But if you could, it would be pretty easy to make a good training setup like you want. Save a state where you're edgeguarding Marth, say. Write a bot that tries to recover. When Marth dies or gets back to the edge, reset back to the savestate. This could all be done with libmelee as it is, assuming you figure out the savestate thing.

**Comment by flux627** [comment]
Right, that's exactly what I'm thinking. I could run a "set-up" macro that controls both characters, puts the characters in their positions, and saves the state. From there you wouldn't ever have to run that again, given the savestate doesn't get overwritten.

What the memory-changing feature would help with here is programmatically changing percentage. I would currently have to create a set-up macro for each percentage, manually hitting the opponent.

**Comment by altf4** [comment]
I'm gonna mark this down as a "wontfix" for now. I'm pretty confident that I'm not going to have time to work on this sort of feature. If anyone else does, have at it.
