### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by altf4** [altf4/libmelee#2]
I'd like to have Windows support in libmelee, but there's some roadblocks:

1) Dolphin talks to libmelee via its MemoryWatcher feature, using a Unix Domain Socket as the transport. As the name suggests, this doesn't exist on Windows. Some other roughly equivalent transport will have to be made there, and integrated into Dolphin's code.

2) Paths in libmelee will have to be updated to read Dolphin's config files on a Windows filesystem.

**Comment by vladfi1** [comment]
In July I made a [custom dolphin fork](https://github.com/vladfi1/dolphin/tree/win-mw) whose MemoryWatcher and Pipe inputs work on Windows. Let me know if you're interested in using it; you can also look at the phillip code to see how to interact with it.

**Comment by altf4** [comment]
Ah right, the ZMQ approach right? I like it... but ideally it would be something that could be pulled into upstream dolphin.

**Comment by vladfi1** [comment]
I believe they may accept it if I switch from zmq to a very similar tool called nanomsg (which I already use in another part of phillip). I'll look into possibly getting it merged upstream when I get some more free time.

**Comment by altf4** [comment]
> some more free time

You and me both. :)

But yea, I'm glad to accept whatever process if it'll get accepted into mainline dolphin. Would be more than happy to include it here in libmelee.

**Comment by 5plintered** [comment]
Hi all trying to get a first time installation of meleelib and dolphin running. I have missing modules can anyone help?

F:\Users\5plintered\Anaconda3\envs\SmashEnv\python.exe "F:/Projects/Missing Brother/MeleeLibrary/example.py"
Traceback (most recent call last):
  File "F:/Projects/Missing Brother/MeleeLibrary/example.py", line 2, in <module>
    import melee
  File "F:\Projects\Missing Brother\MeleeLibrary\melee\__init__.py", line 5, in <module>
    from melee.dolphin import Dolphin
  File "F:\Projects\Missing Brother\MeleeLibrary\melee\dolphin.py", line 1, in <module>
    import os, pwd, shutil, subprocess
ModuleNotFoundError: No module named 'pwd'

**Comment by altf4** [comment]
libmelee does not currently support Windows, sorry. Though I would like to make it happen.

**Comment by wimccall** [comment]
Is this still being looked into? I want to use this feature if possible. Alternatively, what is the best way to squeeze performance out of a linux build of dolphin? I have a ubuntu-MATE install and I built several versions of dolphin, but even in the most recent version, dolphin performance is a problem on linux (one I don't experience on Windows)

**Comment by altf4** [comment]
Not actively. I started to look into it a while back, and the Windows port part of it is actually not all that hard. But if we're going to all this trouble, this really ought to be something that can be upstreamed into Dolphin proper. And to make THAT happen, we'll need to rearchitecture things in a bigger way.

**Comment by wimccall** [comment]
Okay, thanks. I'll try and adapt the ZMQ solution from phillip for now.

**Comment by altf4** [comment]
Yea, Vlad's ZMQ implementation was good, but has about 0 chance of being accepted into upstream dolphin. :) They don't want the dependency. Works fine though.

**Comment by KevinCranmer** [comment]
> Okay, thanks. I'll try and adapt the ZMQ solution from phillip for now.

Did you get this working for windows? And would you be willing to share your solution?

**Comment by altf4** [comment]
Windows support is fully here! yay!
