### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by Poilon** [altf4/libmelee#20]
As mentioned, the MacOS support is supposed to work, but it's not really the case.

When the folders `MemoryWatch` is in my `Application\ Support/Dolphin`, I keep getting a pointer error when launching any game.
<img width="727" alt="capture d ecran 2017-09-15 a 16 31 05" src="https://user-images.githubusercontent.com/126802/30487310-5f815770-9a33-11e7-8065-954ab9410063.png">
<img width="799" alt="capture d ecran 2017-09-15 a 16 31 33" src="https://user-images.githubusercontent.com/126802/30487311-5f85a258-9a33-11e7-9275-4762c47e3e64.png">

Having full mac support would be a blast, thanks

**Comment by altf4** [comment]
Are you running the right version of Dophin? Looks like you might not be.

Go into Help -> About. It should look like this:

![image](https://user-images.githubusercontent.com/609563/29752047-7946b178-8b0b-11e7-98d0-099324a4e809.png)

**Comment by Poilon** [comment]
Ok, I thought your fork was directly coded into master, not in a branch. My bad. Works wonderfully.
