### ISSUE TITLE
Support bot vs bot :enhancement

### ISSUE THREAD

**Issue by edisonhuff** [altf4/libmelee#21]
Haven't tried since 0.52 but I would really enjoy being able to test bots against each other.
Do you plan on supporting a bot vs bot ecosystem?
(am attempting to adapt smashbot to play falco, have a friend who is thinking about a rest bot)

**Comment by altf4** [comment]
It already does, just that you have to make both bots play on the same process. I need to refactor a few things in SmashBot to better demonstrate how this works.

That said, I would ideally like to also support multiple AIs connected to the same Dolphin independently of one another. The trouble here is that Dolphin's MemoryWatcher feature uses unix domain sockets to spit out the game's state. And you can't read the socket from multiple processes. They don't multiplex.

What we COULD do is to run a multiplexing daemon. It would ingest the one domain socket from Dolphin and produce N new ones that AIs could read from.

**Comment by altf4** [comment]
Done!

See: https://www.youtube.com/watch?v=kxwPr9oxUMw&feature=youtu.be

The SmashBot code has a more usable example of what this looks like, too. Maybe I should add that to the libmelee example.py? It's really a tiny change... eh...
