### ISSUE TITLE
Feature Request: Auto select ai character

### ISSUE THREAD

**Issue by hermesespinola** [altf4/libmelee#23]
It would be nice if I could identify what character is selected for the AI (I'm currently selecting it manually with a controller) instead of selecting it when calling the script (like in the example). The idea is that I will be able to change the RL player depending on the selection instead of restarting dolphin, which is kind of annoying. I would like to work on this, but, any ideas of where could I start @altf4?

**Comment by altf4** [comment]
You should be able to do this already. Shouldn't need to manually select a character with a controller.

In the player's state, the "character" attribute gives you an enum of the currently selected character. If you want to select a new character, I made the helper function selectcharacter, as shown in the example.py.

**Comment by hermesespinola** [comment]
Hi altf4, this is out of topic, but, I just wanted to know if there is some way to know which projectiles belongs to a player? As I can see in the code, there is a field called 'opponent_owned' in the class Projectile but it is always True.

**Comment by altf4** [comment]
lol, looks like I just never set opponent_owned to anything. That would do it!

The information should be there, it just needs to get used. I'll have to fix that. Thanks for noticing it.

**Comment by altf4** [comment]
Item ownership is in the latest build now!

**Comment by hermesespinola** [comment]
Thanks!
