### ISSUE TITLE
Controller won't connect on latest dolphin rebased, memorywatcher-rebased version doesn't work

### ISSUE THREAD

**Issue by soule** [altf4/libmelee#36]
Hi,

I tried to install the version of memorywatcher-rebased dolphin you linked, but it won't run properly on linux (ubuntu 18.04).

I then downloaded latest dolphin off github and rebased your changes on to it, however, the controller won't run. The code in example.py makes it all the way to the controller connection line but does not progress past that.

Do you have any fix for making the controller work? Any help would be amazing, as we are on a deadline for a project.

Thanks

**Comment by altf4** [comment]
I fixed some merge conflicts and updated the dolphin build. Try this perhaps: https://github.com/altf4/dolphin (master branch)

**Comment by altf4** [comment]
Check out master branch of libmelee for instructions. It's all working now. Re-read the instructions though, since a bunch has changed
