### ISSUE TITLE
Support for older slp replays

### ISSUE THREAD

**Issue by lukas-blecher** [altf4/libmelee#43]
Hi altf4,
I really appreciate the support of slp files in the console class.

I've noticed that older replay files (I've tested it with a file from [Genesis 7](https://slippi.gg/tournament/111517)) only ever have `EventType`s `PRE_FRAME` and `POST_FRAME` (and `GAME_END` once). The process is then stuck in this [loop](https://github.com/altf4/libmelee/blob/4bcede0991f70fe275998be78ff13d3791bb4cf6/melee/console.py#L253) since `frame_ended` won't turn `True`.

Is there hope for these older replay files?

**Comment by altf4** [comment]
Hmmm, looks like those replays are version 2.0.1. You can see what fields are supported in what version here:
https://github.com/project-slippi/slippi-wiki/blob/master/SPEC.md

In particular, "Frame Bookend" events were added in 3.0.0, which we sort of rely on... :/

**worst case** you can always upgrade the slippi replays by playing them back on dolphin and re-recording them.

But yea, I'll have to figure out what the oldest version of SLP file libmelee is going to support. It might be 3.0.0, not sure yet.

**Comment by lukas-blecher** [comment]
Since "new fields added to a payload are added to the end" couldn't you just check if the event code is decreasing from one iteration to the next? That would also mark a new frame. 

I've implemented it here in [my fork](https://github.com/lukas-blecher/libmelee).

**Comment by altf4** [comment]
You'd also be missing on some important info introduced in 3.0.0, like projectiles. Maybe that's okay?

**Comment by lukas-blecher** [comment]
Because the corresponding information is not saved in previous versions, correct?
I was just hoping to get a game state that is not None from older relay files. 

Thank you for the answers and insights.
