### ISSUE TITLE
Notes on current proposed changes

### ISSUE THREAD

**Issue by JoshuaMcGraw** [altf4/libmelee#48]
Optional unit-circle based stick tilt, e.g. tilt_analog_unit(x, y) where x and y are unit vectors, or tilt_unit_degrees(float). tilt_unit_degrees could be useful for any change in degrees over time. 

Character detection on Slippi occasionally faults if both players select the same character. (Or maybe the other player is also a bot who is performing the same character check...?)

controller.empty_input() renamed to controller.release_all()

**Comment by altf4** [comment]
Number two is a bug for sure. I'll make a separate ticket for it. I know why it happens, will explain there

**Comment by altf4** [comment]
#50

**Comment by altf4** [comment]
The other two things I added. Made a `release_all()` function and `tilt_analog_unit()`.
