### ISSUE TITLE
installation errors with Python 3.8.5

### ISSUE THREAD

**Issue by dillonmarquard** [altf4/libmelee#53]
Issues related to installing are likely related to python 3.8.5 depreciated methods.
This is fixed by downgrading to python 3.7.

**Comment by altf4** [comment]
Oh, do you know what methods? I've been running on 3.6.9, but anticipate upgrading soon.

**Comment by dillonmarquard** [comment]
No, but I think pip was failing when it tried to use wheel, so that would be the best direction to check. To clarify, I am specifically using python 3.7.9

**Comment by altf4** [comment]
Working on my windows machine with Python 3.8.6. So I think this is working now? I was also never able to really reproduce it to begin with so... Closing for now.
