### ISSUE TITLE
Can someone make a video tutorial for libmelee setup?

### ISSUE THREAD

**Issue by SpaceCowboy3514** [altf4/libmelee#54]
I'm bad at following written directions

**Comment by altf4** [comment]
The hardest part of getting libmelee setup is building Ishiiruka from source. But that'll go away once spectator mode lands in Slippi. So just hang on a bit.

That said, I actually do want some videos for explaining other things. I already made one, in fact. Not sure if I want to reshoot it. But anyway, yea that is a thing.
