### ISSUE TITLE
Wrong Dolphin Config Path on non-Linux Systems

### ISSUE THREAD

**Issue by EdgeGnW** [altf4/libmelee#59]
I followed the setup instructions but got a parsing error. It turns out the `_get_dolphin_config_path()`-function in console.py returns the Dolphin executable path on non-Linux systems. (Line 772)
Adding `"/User/Config/"` the same way it does for Linux solved the issue for me.

**Comment by altf4** [comment]
Ah, yea I messed that up. Try version 0.19.5, should be fixed.

**Comment by EdgeGnW** [comment]
Thank you, it works now.
