### ISSUE TITLE
Support Sheik and IC's

### ISSUE THREAD

**Issue by altf4** [altf4/libmelee#6]
Melee stores Sheik and Zelda as separate characters, both of which exist at all times. When you "transform", you're actually not changing into Sheik (in terms of the game's data structures) but rather Zelda goes into an invisible and inactive state. It's just like Nana/Popo.

libmelee currently doesn't even see Sheik / Nana, since we're only looking at one character. Look into what it would take to see Sheik / Nana. (It might be something as simple as an addition to Locations.txt, or it might be complicated and require a Dolphin patch)

**Comment by vladfi1** [comment]
What I did for phillip was to ban down B as Sheik or Zelda and make sure to hold A before game start if Sheik. Peach's toad also resulted is some weird stuff so I banned that too.

Obviously these won't be as effective if the opponent is a human or the in-game cpu.

**Comment by altf4** [comment]
Sheik support is in. Not ICs yet, tho.

**Comment by altf4** [comment]
Nana added in 0.21.0, IC support is in
