### ISSUE TITLE
Stick input has no effect 

### ISSUE THREAD

**Issue by JakeSpitznagel** [altf4/libmelee#60]
Using `controller.tilt_stick(melee.enums.Button.BUTTON_MAIN, 0.5, 1)` seems to set the controller state, but the emulator doesn't seem to react to it and makes it impossible to choose a character, or move while in game. I am able to provide other inputs, including in the menus. 

This is on Windows w/ libmelee v. 0.19.4

**Comment by altf4** [comment]
I did have something messed up in 0.19.4 on windows just now. Can you try upgrading to 0.19.5 and try again?

**Comment by JakeSpitznagel** [comment]
I've upgraded to 0.19.5 and the problem still occurs. 

I've also traced it a bit and it seems like the `controller._write()` call successfully sends the command to the pipe, though I'm not sure if that helps.

**Comment by altf4** [comment]
Are you running the example.py? Or something you wrote? If you wrote it, could you post/link it?

**Comment by JakeSpitznagel** [comment]
I am running (a slightly modified version of) example.py which I have attached in a zip file.

(mostly just testing the API)

[example.zip](https://github.com/altf4/libmelee/files/5449361/example.zip)

**Comment by altf4** [comment]
I ran your script and it seemed to work for me? I'm not sure what it's supposed to do exactly, but it went into game just fine and the character moved around.

**Comment by JakeSpitznagel** [comment]
Strange, for me the character will just stand there and neutral b, I will try to debug things on my end. Do you have any ideas where I should start?

P.S. Thanks a lot for helping me out.

**Comment by altf4** [comment]
What is it supposed to be doing, exactly? Looks like it holds right 99/100 frames, and then presses B 1/100 frames? That is exactly what I'm seeing. Fox runs to the right, and every once in a while throws out a laser.

**Comment by JakeSpitznagel** [comment]
That's basically it, I was trying to create a scenario that showed that I could accept button inputs but not stick inputs. It definitely sounds like the issue is somewhere on my end. My hunch is I have Slippi configured incorrectly or something messed up in my .ini files

I also have to manually select the character via the other controller to actually get into game, but that is a result of the same issue.

**Comment by altf4** [comment]
Did you apply the gecko codes linked to in the readme?

Those codes add support for getting menu state information. So without them, libmelee can't "see" the menus.

**Comment by JakeSpitznagel** [comment]
I did, and I am able to traverse the menus after changing the `controller.tilt_analog(enums.Button.BUTTON_MAIN, .5, 0)` to a `controller.press_button(enums.Button.BUTTON_D_DOWN)` in `menuhelper.choose_versus_mode()` unfortunately this is simply a workaround that applies only to the menus
.

**Comment by altf4** [comment]
I dunno. If you've been working with a local copy of libmelee, perhaps try using the version in pip. Just copy `example.py` out separately and run it on its own. (without an adjacent melee/ folder)

**Comment by JakeSpitznagel** [comment]
Interesting, I changed the port (-p flag) that the controller was using from 2 to 1, and it works. So something must be messed up with my controller config or named pipe. (?)

I must confess Windows named pipes are a complete mystery to me.

**Comment by altf4** [comment]
Named pipes on windows are basically their own thing and bare almost no resemblance to named pipes in Unix. They should have just called them something else.

Anyway, yea perhaps there is something wrong with the controller config. You could try manually looking at it in the dolphin GUI. Or perhaps deleting the config and starting over.

**Comment by JakeSpitznagel** [comment]
Either way I think that's on me to try and figure out. So I think we can mark this issue as closed? 

Thanks a ton for helping me debug this and being so responsive. :) I know debugging random user's un-reproducible bugs isn't the most fun but you were super helpful, and I appreciated it.

**Comment by altf4** [comment]
np!
