### ISSUE TITLE
Console can not connect to SLP file. It treats the slp path as dolphin directory

### ISSUE THREAD

**Issue by sirgarfieldc** [altf4/libmelee#67]
<img width="674" alt="Screen Shot 2020-11-29 at 6 56 23 PM" src="https://user-images.githubusercontent.com/14815380/100557062-94dc6900-3274-11eb-8bd8-2c1b8ca1a7a2.png">

I can not reproduce the example above with melee (0.21.1)

When I run 
```
console = melee.Console(is_dolphin=False,
                allow_old_version=False,
                path="./debug/(YOTB) Fox vs Falcon (MN) [FD] Game_20200222T153115.slp"
                )

console.connect()
```
I get
<img width="841" alt="Screen Shot 2020-11-29 at 6 57 43 PM" src="https://user-images.githubusercontent.com/14815380/100557092-c48b7100-3274-11eb-99cd-39fb88255330.png">

Console seems to treat slp path as dolphin directory.

How should I get console to connect to SLP file ?

**Comment by altf4** [comment]
Yea, I actually just noticed that bug this morning myself. It's already fixed in the master branch, if you want to use that. I'll cut a new version (0.21.2) soon that will have the fix

**Comment by altf4** [comment]
Fixed as of 0.21.2. Let me know if it works for you

**Comment by sirgarfieldc** [comment]
Connect Console to SLP works with 0.21.2 for replay recorded in Slippi Dolphin Version 2.2.3.

However, When I attempt to connect and step through SLP files with version 2.0.1. 

I got  SlippiVersionTooLow: 2.0.1

What is the lowest version allowed  for this functionality ?

**Comment by altf4** [comment]
You just need to set `allow_old_version`, like here: 

https://github.com/altf4/libmelee/blob/master/example_file.py#L5
