### ISSUE TITLE
Add controller visualization

### ISSUE THREAD

**Issue by altf4** [altf4/libmelee#7]
Something basically like this: 

https://youtu.be/_jdupqY9oxM?t=1m30s

Not sure of the best way to make it actually work yet.

**Comment by ghost** [comment]
Just the bot actions? or something like SF training mode?
https://i.ytimg.com/vi/Wp9zJdJBtII/hqdefault.jpg

**Comment by altf4** [comment]
I was thinking just for the bot's actions. As a cool "omg, look at those inputs" sort of cool-factor. Also, libmelee (deliberately) can't see what buttons the other players are pressing, so there's that.

**Comment by altf4** [comment]
Ehhh, I don't think this is actually something the API should have
