### ISSUE TITLE
Game state does not progress when in a menu.

### ISSUE THREAD

**Issue by christopher-pieper** [altf4/libmelee#70]
I am trying to set up the bot with the example.py file, but I can't seem to get it to use the menu helper. Once I'm in a match, the ai works fine, but during character select (or any other menu) the code pauses and doesn't pass a gamestate. Because of this I can't access the gamestate.menu_state parameter when in menus, and thus cant reach the menu helper function. Has anybody else had this same problem or know of a solution? Sorry if this has already been answered, I am new to Libmelee.

**Comment by altf4** [comment]
You have not correctly installed the custom gecko codes listed in the readme. Do that and try again.

**Comment by christopher-pieper** [comment]
This worked, thank you!
