### ISSUE TITLE
console.step() hanging on Mac OSX

### ISSUE THREAD

**Issue by cwlittle** [altf4/libmelee#73]
I'm having a bit of issue getting libmelee to interact with my console instance. I can get slippi opened and the iso opened, but couldn't get the simple menu helper to interact with the console. 
After a bit of debugging, I found that console.step() is hanging. The __dict__ attribute of the object shows connected: False after console.connect() returns True without erroring out for failed connection. After I try to run the program and the console.step() hangs, my slippi instance will crash after trying to select new controllers, even opening from the executable independent of libmelee. So there seems to be some permanent breaking modification of slippi configuration due to libmelee in my case.

**Comment by altf4** [comment]
Make sure you're using the libmelee gecko codes, as shown in the readme. Sounds like you don't. (Note that sometimes dolphin will clobber them if there's an update. So you might need to re-download them)

**Comment by cwlittle** [comment]
Reran this on a fresh install of slippi with new iso and gecko codes and still have the same issues.

**Comment by altf4** [comment]
If you run example.py, and manually select the bot's character for it and go into game, does it multishine?

**Comment by cwlittle** [comment]
Yes

**Comment by altf4** [comment]
That means you're not using the right gecko codes.

The codes add support for menu state information, which is why the bot can't "see" the menus.

**Comment by laeckerv** [comment]
Hi, I have exactly the same issue with hanging console.step() call, and I'm using the gecko codes from the [readme](https://github.com/altf4/slippi-ssbm-asm/blob/libmelee/Output/Netplay/GALE01r2.ini)

![image](https://user-images.githubusercontent.com/1636489/126236583-fc8b56b5-faf3-4e11-98ca-363f3e039d94.png)

**Comment by altf4** [comment]
Are you using the libmelee example.py? Try manually selecting the bot's character and go into the game. Does step() proceed then?

**Comment by laeckerv** [comment]
I tried it with the example.py as well. It seems like there is more stuff broken. I watched your tutorial video and it seems like 
the game should switch to the character selection screen? It doesn't do that either., it's stuck in the 1 Player -> Online Play.

![image](https://user-images.githubusercontent.com/1636489/126295642-f7e3d7fc-6370-45f7-8b76-02540f26da4b.png)

I navigated manually and started a game, but step() doesn't process.

I'm using:
- melee 0.30.3
- Slippy Dolphin 2.3.1 ![image](https://user-images.githubusercontent.com/1636489/126294940-55a72982-65a1-4eb0-8945-f3baf6ff4f8b.png)

**Comment by altf4** [comment]
Sounds like libmelee isn't connecting to dolphin. Is there any output in the terminal when you launch it?

**Comment by laeckerv** [comment]
Yeah.

```python
console.run(args.iso)

# without this sleep it would run into "ERRPR: Failed to connect to the console."
sleep(4)

print("Connecting to console...")

if not console.connect():
    print("ERROR: Failed to connect to the console.")
    sys.exit(-1)
else:
    print("Console connected")
```

**Comment by altf4** [comment]
So did it connect or not?

**Comment by laeckerv** [comment]
It seems to connect if I add that sleep in there. However in dolphin it only stays at "1 Player -> Online Play".

**Comment by laeckerv** [comment]
![image](https://user-images.githubusercontent.com/1636489/126554400-7b88a542-04ca-460f-88af-87bb7c6d50de.png)

![image](https://user-images.githubusercontent.com/1636489/126554605-e3286ff3-f4ef-4e9e-9249-42983bf8be50.png)

**Comment by altf4** [comment]
If you're connected, but it doesn't move at the menu, then you're almost surely not using the correct gecko codes. Note that they get clobbered when there's a Slippi update, so it's easy for them to get replaced. Double check that.
