### ISSUE TITLE
Question about controller .ini and pipe input like in libmelee 

### ISSUE THREAD

**Issue by neobis001** [altf4/libmelee#75]
I should probably ask this in Project Slippi, but I wanted to ask it here because you were the one who wrote the pipes code for Slippi, and maybe you'd get notified about it more easily.

Anyways, I took a look at your "Add named pipe input for Windows" [commit](https://github.com/project-slippi/Ishiiruka/commit/87dc83e7018b2e626eca35b402b2c6a4234bfaec#diff-d72f8c46d8cf2dd2faaf4f3726dcb1e1674fdf2d4c5e264d4fa5a9bba8d5bc21) and pipe code here in [libmelee](https://github.com/altf4/libmelee/blob/master/melee/controller.py), and I used them in my own Dolphin.

I used slippibot.ini from that commit. When I try to set the "Analog L" input to 0.0 like below, the Controller menu shows "Analog L" to be half on.

The related .ini line is:
----triggers/l-analog = Axis L -+
I think these lines split the "Analog L" in half, with the "-" axis taking the left half and the "+" axis taking the right half. I think "0.0" is the point between the axes, which is why "Analog L" is set to 50% below.

![axis-minus-plus](https://user-images.githubusercontent.com/10540174/124666541-10357700-de63-11eb-853f-f88f56f009bf.png)

=====================

I did some searching. I found spxtr's p3 project had an [example_gc_profile.ini](https://github.com/spxtr/p3/blob/master/example_gc_profile.ini).

The line he writes for "Analog L" is:
----Triggers/L-Analog = `Axis L +`
So I try just using "+" instead of "-+" in my .ini, and setting "Analog L" to 0.0 turns it off like I expected. I think in this case, now the "+" axis is mapped to the entire "Analog L" range, with 0.0 being at the far left. I show that below.  

![axis-plus](https://user-images.githubusercontent.com/10540174/124667140-d9139580-de63-11eb-9b32-0b6518655f1c.png)

=====================

My question is should the .ini for doing pipes input have "-+" for the triggers or "+"? "+" makes most sense to me, but I don't know if "-+" worked for you for setting the Analog Triggers completely off. I'm assuming it did, if you use it regularly for your Smash AI, so I'm also thinking I may have done the input incorrectly.

**Comment by altf4** [comment]
Oh hey, somehow I missed this question the firs time. Sorry about that.

I'm not sure, honestly :( I don't really know the difference between the two. I just sorta copied how the other configs had it, and it worked.

**Comment by neobis001** [comment]
@altf4 Wow, this was from a long time back. Alright, that's okay. Thanks for replying. As long as I can get "SET L 0.0\n" to get the trigger completely off, I'm happy. It makes more sense to me than having it turn the trigger 50% on.

By the way, is there an easier way to contact you? Like Discord, email, or Project Slippi itself? It'd be cool to say hi sometime and ask general things, like what's new w/ libmelee.

**Comment by altf4** [comment]
yea, I'm usually in the Slippi discord. You can hit me up there
