### ISSUE TITLE
Issue with MenuHelper

### ISSUE THREAD

**Issue by dkadillak** [altf4/libmelee#76]
I downloaded Dolphin with Slippi (as opposed to using the slippi launcher) and have run into a problem using the melee library since the 2.3.2 update. 

Description of problem:
*I'm running example.py*
When entering the  main loop the current gamestate is returned with a ``console.step()`` call. ``console.step()`` then calls ``_slippstream.dispatch(self._polling_mode)`` which is where it gets stuck in an an infinite loop. The example.py script boots dolphin, runs melee and stops at the home menu because of this issue

Has anyone run into this? Does anyone have a suggestion on how to proceed trouble shooting?

Versions of python, Dolphin with Slippi, and melee library i'm using:
* python: 3.9.1
*  melee: 0.30.3
* Dolphin with Slippi: 2.3.2

Thank you!

**Comment by altf4** [comment]
Are you sure it's stuck in an infinite loop? Or is it just blocking?

Make doubly sure you're using the correct libmelee gecko codes. That's probably you're issue.
