### ISSUE TITLE
Fox multishine fails

### ISSUE THREAD

**Issue by jackeown** [altf4/libmelee#84]
I was running the example.py file and for me fox doesn't successfully multishine. He just jumps in the air and shines fully above ground repeatedly. I can't for the life of me figure out why. Do you know why this could be happening?

**Comment by altf4** [comment]
Sounds like you have local delay on. There's a gecko code to turn it off. (It's a default one)

Look in the bottom right of the screen, does it say "2f"?

**Comment by jackeown** [comment]
I saw no '2f'. Do you know the name of the gecko code? I'm using "Faster
Melee - Slippy (2.3.3)"

Thanks,
Jack

**Comment by altf4** [comment]
Recommended: Apply Delay to All In-Game Scenes

**Comment by jackeown** [comment]
Yes it was that. Thank you
