### ISSUE TITLE
console.step() not returning unless in-game

### ISSUE THREAD

**Issue by Retroroid** [altf4/libmelee#86]
As title says, I load up the example program, change the default path for slippi, and when starting it, the first gamestate = console.step() will not return until a game is entered. From what I have seen in the documentation and examples, it should have no trouble returning and recognizing the menus.

I suspect that this is due to some changes in the slippi launcher/dolphin edit, but I don't really know anywhere near enough to have any useful input.

Let me know if there's anything I should do to help explain further.

**Comment by altf4** [comment]
Sounds like you don't have the libmelee gecko codes installed. Try reinstalling them.

Note that dolphin will clobber them whenever there's an update. So you might need to install the codes again even if it feels like you JUST did.

**Comment by Retroroid** [comment]
That did it! I definitely replaced the config file before with the correct code from the github link, but it seems dolphin bonked the file like you said. Might have been an update or something with the way i was modifying or saving them, but it seems to work fine now, thank you very much for the incredibly quick response! I look forward to working with this library a lot :)
